### PR TITLE
fix: fixed bcrypt import issue

### PR DESCRIPTION
**Pull request by Youngemmy5956**
The issue is that bcrypt.js is not exporting default. but i have fixed and tested it... It's now working.

### CODE REVIEW

**Review by arnb-smnta — COMMENTED** [review]
I am not a collaborator but i think you need to install the project with yarn locally to avoid upload of package-lock.json and yarn.lock then push the commits as suggested in docs and readme

**Comment by Youngemmy5956** [comment]
@arnb-smnta done

**Review by Youngemmy5956 — COMMENTED** [review]
Pls am waiting for approval on this..

**Comment by Youngemmy5956** [comment]
I created a new pull request for address not found

**Comment by wajeshubham** [comment]
Thank you for your PR but, the issue #106 that this PR targeting is not yet confirmed as a bug. Upon testing everything is working fine with original code we are waiting for confirmation from the author of the error.

**Pull request closed without merging**
