### PR TITLE
Feat/local mongodb connection

### PR DESCRIPTION
**Pull request by plutack1**
This was to solve a problem i have.
I run a Linux on my PC. It has MongoDB installed as a service that runs on startup since i didn't want to have duplicate MongoDB for save space and also to have all database in a single place. i decided to connect the docker container to the MongoDB running locally.

### CODE REVIEW

**Comment by plutack1** [comment]
If this is considered.


I should add i am not sure if 
“environment:
       - MONGODB_URI=mongodb://host.docker.internal:27017”
Is needed since it is present in the env sample file already. But as it is.it works so i didn’t bother to check. I would think it isn’t needed actually

**Comment by plutack1** [comment]
I have also seem to realize that there is no point downloading mongodb image if you have a local docker  hence the new docker compose template and also localhost wont work  as implied  i think… please see links attached.

**Comment by wajeshubham** [comment]
> If this is considered.
> 
> I should add i am not sure if “environment: - MONGODB_URI=mongodb://host.docker.internal:27017” Is needed since it is present in the env sample file already. But as it is.it works so i didn’t bother to check. I would think it isn’t needed actually

@plutack1 Thanks for the PR.

It would be great if you could include the environment vars in the `.env` file instead of the compose file to avoid confusion and conflicts. 

We have a `.env.sample` file where we would like to include a commented line: `MONGODB_URI=mongodb://host.docker.internal:27017`. Please add this line with a description indicating who should use it, along with some contextual information.

@jwala-anirudh, could you please review the PR on the Linux machine and provide your valuable feedback? Your insights would be greatly appreciated. Thank you!

**Comment by plutack1** [comment]
Neccessary changes have been made.

**Comment by wajeshubham** [comment]
Hi @plutack1 ,

Thank you for taking the time to submit your PR and suggesting improvements to our project.

After carefully reviewing the changes and considering our current setup, we've decided to not merge this PR at this time. However, we truly appreciate your effort and the thoughtfulness behind your suggestion.

It's worth noting that while Docker is popular, our current user base may not heavily rely on Docker or have experience with Docker networks. Additionally, our codebase, including the creation of a Docker Compose file with both our app and MongoDB image, should provide a smoother experience for developers without requiring them to interact with Docker networks directly.

Instead of merging this PR, we believe it could be beneficial to document your proposed solution as an alternative approach in our project's README or documentation. This way, future developers who encounter similar issues with Docker networking can benefit from your insight and find a solution.

Again, we appreciate your contribution and the time you've invested in improving our project. If you have any further suggestions or ideas, please don't hesitate to share them with us.

Thank you,
FreeAPI team

**Pull request closed without merging**
