### PR TITLE
Pre hook added for find query of user schema for password remove

### PR DESCRIPTION
**Pull request by Harsh-Dhorajia**
In User schema, I had added the pre hook for password remove for find queries.

### CODE REVIEW

**Comment by jwala-anirudh** [comment]
Harsh, please check for the usage of `password` value in all the controllers that are using user schema, if retrieved value is having password in use then it will break the functionality. So cover the fetch on password parameter on select again.

Would appreciate if you can add some comment docs for the newly introduced code.

**Comment by Harsh-Dhorajia** [comment]
Thanks for reviewing @jwala-anirudh . I had updated the according to your review.

**Comment by wajeshubham** [comment]
@Harsh-Dhorajia I don't think `isPasswordCorrect` method is getting affected due to addition or absence of the pre `find` hook.

**Comment by Harsh-Dhorajia** [comment]
@wajeshubham In **isPasswordCorrect** method previously, password was fetched by **this.password**. But after pre find hook, in this we don't get password. So I had updated accordingly.

**Review by wajeshubham — COMMENTED** [review]
@Harsh-Dhorajia 

After conducting a thorough review of the PR, we have carefully considered the addition of the pre-hook for the password field. 

While it's an interesting concept, we believe it might introduce complexities or unexpected behaviour in future maintenance as the application grows. The reason being, the authentication module is the only module which is common and re-used in multiple complex apis like e-commerce, social media and many more in future. Therefore, for now, we think it's best to keep these changes un-merged.

Please know that we genuinely appreciate your efforts and dedication to the FreeAPI project. Your contributions are valuable to us, and we eagerly look forward to more from you. Keep up the fantastic work!

Thank you, and happy coding! 😀

**Pull request closed without merging**
