### PR TITLE
Fixed todos patch api 

### PR DESCRIPTION
**Pull request by sangamesh1439**
Fixes: https://github.com/hiteshchoudhary/apihub/issues/34

Screenshot:
Screenshot 2023-07-24 at 2 13 49 PM

### CODE REVIEW

**Comment by sangamesh1439** [comment]
@wajeshubham  Fixed a small bug in todos, Please review.

**Comment by wajeshubham** [comment]
@sangamesh1439,

Thank you for the PR and for addressing the bug! 😀

While reviewing your PR, I noticed that there are more endpoints that have a similar issue due to the presence of comments in the `requestBody` in the `swagger.yaml`. Here is the list of endpoints that have the same issue:

```js
POST: "/ecommerce/cart/item/{productId}"

POST: "/ecommerce/coupons"
POST: "/ecommerce/coupons/c/apply"
POST: "/ecommerce/coupons/c/remove"

POST: "/ecommerce/addresses"
PATCH: "/ecommerce/addresses/{addressId}"
```

Could you please address these routes and fix the similar issue in these endpoints? Also, check if other endpoints not mentioned here have the same problem. Your assistance would be greatly appreciated! 😃

Kindly give me a thumbs up if you are proceeding with the suggestions.

Cheers!

**Comment by sangamesh1439** [comment]
@wajeshubham  Done

- [x] POST: "/ecommerce/cart/item/{productId}"

- [x] POST: "/ecommerce/coupons"
- [x] POST: "/ecommerce/coupons/c/apply"
- [x] POST: "/ecommerce/coupons/c/remove"

- [x] POST: "/ecommerce/addresses"
- [x] PATCH: "/ecommerce/addresses/{addressId}"

**Review by wajeshubham — APPROVED** [review]
Looks good!

**Pull request merged**
