### PR TITLE
feat: social media app frontend ( react, redux, shadcn )

### PR DESCRIPTION
**Pull request by Rudra-Patel-code**
## Tasks Completed

- [x] Basic project setup completed.
- [x] Shadcn setup for theme toggle
- [x] redux / redux-toolkit boilerplate setup
- [x] Login and Register page created.
- [x] Protected route components created
- [x] created posts and auth slices 
- [x] added infinite scroll feature like instagram

### CODE REVIEW

**Comment by wajeshubham** [comment]
@Rudra-Patel-code any update on the progress? Kindly let us know.

**Comment by Rudra-Patel-code** [comment]
@wajeshubham Yes, I am working on it. It would mostly be done in 10 days.

**Comment by wajeshubham** [comment]
> @wajeshubham Yes, I am working on it. It would mostly be done in 10 days.

Kindly mark PR ready for review once you are done. Thanks!

**Comment by Rudra-Patel-code** [comment]
@wajeshubham I regret to inform i that i will not be able to complete this project because of other commitments. You can close this pr or can assign any other person who is interested in completing this project

**Pull request closed without merging**
