### PR TITLE
Fix #176: Email Verification Error - Token is Invalid or Expired

### LINKED ISSUE #176: Email Verification Error: Token is Invalid or Expired
**Description**
I encountered an issue with the email verification process. The token sent in the verification email does not match the token stored in the database.

**Steps to Reproduce**
1. Register a new user using the API endpoint `http://localhost:8080/api/v1/users/register`.
2. Check the response and the MongoDB database to verify the stored token.
3. Try to verify email using API endpoint `http://localhost:8080/api/v1/users/verify-email/{verificationToken}`
4. Observe the error message.

**Expected Outcome**
Email is verified

**Actual Outcome**
The server responds with a "Token is invalid or expired" error.

**Error Message**
```json
{
  "statusCode": 489,
  "data": null,
  "success": false,
  "errors": [],
  "message": "Token is invalid or expired",
  "stack": "Error: Token is invalid or expired\n    at file:///path/to/user.controllers.js:212:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
}

### PR DESCRIPTION
**Pull request by surajcan30t**
## Subject
Fix for Issue #176 - Email Verification Error Despite Correct Token Entry
## Issue
The email verification process was generating an error even when users entered the correct token.
## Change
- The token was again hashed which should not be done as the token is to be checked inside the database.
- For comparison new Date( ) returns correct time representation
### After new registration
Screenshot (317)
### Token verification
Screenshot (318)
### After verification
Screenshot (319)

### CODE REVIEW

**Review by agareaditya-8055 — APPROVED** [review]
Thank you. Now its working.

**Comment by surajcan30t** [comment]
Welcome and thank you for your review.

**Comment by wajeshubham** [comment]
The implementation is invalid. The actual flow of verification is as follows:

User registers -> a token is generated -> token is hashed and stored in the DB (for security) -> **UNHASHED** (raw) token is sent to the user's email -> One user click the url in the mail, it makes an api call -> in url's path variable we have **UNHASHED** token which we hash first -> compare the hashed raw token with the hashed token present in the DB. 

You cannot simply copy token from DB and make verify email api call that's a security threat. This way anyone can copt token from DB and verify the user.

**Comment by surajcan30t** [comment]
What should be the approach to test that api `/users/verify-email/{verificationToken}`
It should be helpful please let me know.

**Comment by surajcan30t** [comment]
Hey! @wajeshubham waiting for your response.

**Pull request closed without merging**
