### PR TITLE
Dockerized the Frontend Apps 

### PR DESCRIPTION
**Pull request by ahmadrazalab**
**Pull Request Description:**

This pull request introduces several enhancements and adjustments to the FreeAPI open-source project. The changes focus on refining Docker configurations, updating environment variables, and optimizing Dockerfiles. Below is a summary of the modifications made:

---

**.dockerignore:**
- Added exclusion for the `examples` folder in Docker to reduce unnecessary content in the backend container.

**.env.sample:**
- Updated the `MONGODB_URI` variable to provide flexibility when using either a local MongoDB instance or a Dockerized one.

**Backend Dockerfile:**
- Switched the base image to `node:alpine3.18` to decrease the size of the container.

**README-DOCKER.md:**
- Added instructions for running the FreeAPI project with Docker, emphasizing the creation of `.env` files and executing Docker Compose commands.
- Provided a note about customizing the Docker Compose file by commenting out unnecessary containers.

**docker-compose-full.yaml:**
- Dockerfile includes the backend container, Mongo DB with the frontend container of the chat app and todo app to fully dockerize the project 

**Examples/Apps Chat-App/Web/React-Vite-Tailwind/.dockerignore & Dockerfile:**
- Added Docker configurations for the Chat App frontend, including Dockerignore file and Dockerfile for containerization.

**Examples/Apps Todo/Web/React-Vite-Tailwind/.dockerignore & Dockerfile:**
- Incorporated Docker configurations for the Todo App frontend, including Dockerignore file and Dockerfile for containerization.

**Examples/Apps Chat-App/Web/React-Vite-Tailwind/vite.config.ts & Examples/Apps Todo/Web/React-Vite-Tailwind/vite.config.ts:**
- Updated Vite configuration to allow access to the application outside of localhost if we are hosting this service on server using public ips or in ec2.
- it is affective while working will different standalone containers and host this app in AWS Ec2

---

These changes aim to fully dockerize and deploy the FreeAPI project, enhancing its usability and maintainability. This pull request aligns with the project's objectives and contributes to its overall robustness.

Contributing to FreeAPI is a great way to learn about Docker and Docker-compose and how to deploy a 3 tier app like this. Joining in here is a perfect way to do it.

---
**Let's keep making FreeAPI awesome together!**

### CODE REVIEW

**Comment by ahmadrazalab** [comment]
Kindly mark for the review .

**Comment by jwala-anirudh** [comment]
Hi @ahmadrazalab,

Example apps are just for reference to see how FE apps can integrate FreeAPI.app, we do not intend to deploy these anytime. If we really have to dockerise them, at the root we already have a configuration and these child apps can run of different port numbers.

I don't find any benefit of dockerising them, can take feedback from @wajeshubham

**Comment by ahmadrazalab** [comment]
Hi @jwala-anirudh @wajeshubham,
Thank you for your input regarding the Dockerization of the example apps. 

As a DevOps engineer, my main goal with Dockerizing the example apps in FreeAPI is to make the project more accessible and educational for fellow **DevOps engineers** who want to learn about deploying applications using Docker. By including Docker steps in the project, individuals can gain hands-on experience with Docker while working with a **real-world 3-tier architecture** (frontend, backend, and MongoDB).

It serves as a valuable learning tool for understanding Docker's best practices and application containerization. With Docker configurations integrated into the project, users can explore how to build and deploy each component of the application within Docker containers, fostering a deeper understanding of container orchestration and deployment workflows.

If any change is required from my side please let me know am grateful for to contribute.



---
**I am working on this to make it Kubernetes-friendly**
**Upcoming Goals:**  Deploy it in AWS using EKS and will provide the full guide to deploy manifest files,
I think that would it's a great learning curve using this app to deploy in real-world senario.

**Comment by jwala-anirudh** [comment]
We recommend you to file an issue requesting for new enhancements rather than raising a PR directly, I understand your intention. But, example apps are solely for showcasing FreeAPI.app capabilities. As some may not understand from swagger docs. Not sure how addition of Docker / Kubernetes would benefit that goal

I may not be in a position to take decision for merging this change request, would wait until @wajeshubham leaves his thoughts.

Thank you!

**Comment by wajeshubham** [comment]
@ahmadrazalab as of now we are not planning to dockerise the frontend example apps. Those are just to showcase and reference the usage of the FreeAPI apis.

**Pull request closed without merging**
