### PR TITLE
Feat/ Random Products Flutter App

### LINKED ISSUE #79: FRONTEND: Random Products Flutter App
### Frontend App Title

Random Products Flutter App

### Overview

The Random Products App will be built using flutter, and will allow users to browse the different products.

### Detailed Features

1. Home Page - The home page will consist of random products from the API, along with their brand name and a thumbnail.
2. Product Details Page - The product details page will show the product in detail, along with carousel slider for viewing the images, along with its price, rating and an indicator if the stock of the product is close to ending.
3. Search Page - the search bar will allow the users to search for a product, and they will be able to see results for their queries.

### Tech Stack Used

Flutter, Provider

### Built For Platform

mobile

### Project Path

$ROOT_FOLDER/examples/public/randomproducts/mobile/flutter-provider

### PR DESCRIPTION
**Pull request by Sarthak-ONS**
Resolves #79 
Loom: 
https://www.loom.com/share/d67061ca2f074146a50eb5015b3c0d4b?sid=79d4ec7a-2195-4528-9716-798da2b89a0c

### CODE REVIEW

**Comment by jwala-anirudh** [comment]
PR is in draft, @Sarthak-ONS do you want me to review it (or) wait until you complete it?

**Comment by Sarthak-ONS** [comment]
Hi @jwala-anirudh , I will let you know for review.

**Comment by wajeshubham** [comment]
@Sarthak-ONS any update on this?

**Comment by wajeshubham** [comment]
@Sarthak-ONS Reminder on the update

**Comment by Sarthak-ONS** [comment]
Please start reviewing this pr

**Comment by wajeshubham** [comment]
Branch has conflicts with the origin. Please resolve those first. Thank you

**Comment by Sarthak-ONS** [comment]
Ok, I will resolve and share again

**Comment by wajeshubham** [comment]
Any update @Sarthak-ONS ?

**Comment by wajeshubham** [comment]
Closing due to inactivity

**Pull request closed without merging**
