### PR TITLE
feat/ecommerce: Frontend React App

### PR DESCRIPTION
**Pull request by arnb-smnta**
This is the initial skeleton of the e-commerce app

### CODE REVIEW

**Comment by arnb-smnta** [comment]
@jwala-anirudh  can u please review the skeleton if it is ok or not or we need to add anything to the initial skeleton if it is ok can u please merge it me and @mirajhad can work on UI of the pages individually

**Comment by jwala-anirudh** [comment]
Cannot locate `package-lock.json` file

**Comment by jwala-anirudh** [comment]
Looks fine, you can proceed to add more functionality

**Comment by jwala-anirudh** [comment]
To file an issue with all the details of the app, rough design screens (if possible made in excalidraw). Once done & reviewed, then we will
- assign the issue with both of you
- make a branch to work on to avoid conflicts
- you must take ownership to periodically commit changes to it

**Comment by mirajhad** [comment]
Hi @jwala-anirudh, I have added few ss can you review [https://excalidraw.com/#json=8bHUUTSA4VDtSQJh8A2xv,aPA73DespGf9z-kaEO57iw](url)

**Pull request closed without merging**
